# 디버그 모드를 비활성화하고, 모든 엔드포인트를 노출시킨다. 따라서 모든 관리 엔트포인트를 사용할 수 있다
debug: false
management.endpoints.web.exposure.include : "*"

logging:
  level:
    com.fastcampus.fastcampusprojectboard: debug
    org:
      springframework.web.servlet: debug
      hibernate.type.descriptor.sql.BasicBinder : trace
#      hibernate : debug

spring:
  datasource:
# h2 데이터베이스 설정
#    url: jdbc:h2:mem:testdb
#    username: sa
#    driver-class-name: org.h2.Driver
    url: jdbc:mysql://localhost:3306/board
    username: admin
    password: 1q2w3e4r
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    # ddl을 자동으로 수행하므로 테이블을 만들어줄 필요가 없다
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      # hibernate에서 따로 제공하므로 스프링 부트에 문서가 없는 설정
      hibernate:
        # sql 쿼리를 포맷팅
        format_sql: true
        # 복잡 쿼리를 사용할 때 최대 select 사이즈 설정 (n+1 문제 해결방안)
        default_batch_fetch_size: 100
    # osiv 옵션을 해제한다
    open-in-view: false


#  h2:
#    h2 웹 콘솔 활성화
#    console:
#      enabled: true
  sql:
    init:
      # date.sql 실행 시기 설정 ~ embedded : 테스트 환경에서만, always : 항상, never : 비활성화
      mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  thymeleaf3:
    decoupled-logic: true
--- # 기본 document

spring:
  config.activate.on-profile: testdb
  # h2를 mysql과 같은 환경으로 바꿔서 동작시키는 방법 ~ 호환성 모드
  datasource:
    url: jdbc:h2:mem:board;mode=mysql
    driverClassName: org.h2.Driver
  sql.init.mode: always
  # 문서화가 안되어 있음 ~ 테스트용 디비 사용 전역설정
  test.database.replace: none



